<<<<<<< HEAD
from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='https://discordapp.com/api/webhooks/1082292146561896458/73q5lvnDrP05e3ANN_kasD2JkfW9pfD1P4VdRCO0IeAMkXnhatZwT1xNj0Q3ua6un4LE', username="BANANA")

embed = DiscordEmbed(title='BANANA', description='I am banana', color='ffffff')
embed.set_author(name='August', url='https://github.com/lovvskillz', icon_url='https://cdn.discordapp.com/emojis/1013591314199220304.gif?size=96&quality=lossless')
embed.set_footer(text='I love banana')
embed.set_timestamp()
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')


webhook.add_embed(embed)
=======
from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='https://discordapp.com/api/webhooks/1082292146561896458/73q5lvnDrP05e3ANN_kasD2JkfW9pfD1P4VdRCO0IeAMkXnhatZwT1xNj0Q3ua6un4LE', username="BANANA")

embed = DiscordEmbed(title='BANANA', description='I am banana', color='ffffff')
embed.set_author(name='August', url='https://github.com/lovvskillz', icon_url='https://cdn.discordapp.com/emojis/1013591314199220304.gif?size=96&quality=lossless')
embed.set_footer(text='I love banana')
embed.set_timestamp()
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')
embed.add_embed_field(name='อยากกินกล้วย', value='กล้วย')


webhook.add_embed(embed)
>>>>>>> 80ee62ea7d1f9be315d76ce9ef7232b7c5380a0d
response = webhook.execute()